void free_draw_input(int x, int y,int headinglength, int width, int hieght, int middle, int ch);
void Alphabets(int start, int end, char ch, int x, int y);
void numbers(int start, int end, char ch, int x, int y);
void square_type(int size,char ch,int fill,int x,int y);
void triangle_type(int rows,int type, int fill, char shape, char ch, char side, int x, int y);
void parallelogram_type(int width,int fill, int hieght, char ch, int x, int y);
void trapezium_type(int base1, int base2, int fill, char ch, int x, int y);
void circle_type(int size,int fill, char ch, int x, int y);
void diamond_type(int size,int fill, char ch, int x, int y);
void star_type(int rows,int type, char ch, int x, int y);
void opendirectory(char str[]);
void viewfile();
void savefiledefault();
void savefile(char path[], FILE *fptr);
void openfile(char path[], FILE *fptr);
void call_line(char ch, int size, int x, int y);
void call_heart(int size, char ch, int x, int y);
void call_textbox(int width, int hieght, int x, int y);
void call_pentagon(int size, char ch, int x, int y);
void call_hexagon(int size, char ch, int x, int y);
void call_kite(int rows, char ch, int x, int y);